plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.gemspec'

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 450

Naming/FileName:
  Exclude:
    - 'lib/fluent-plugin-sumologic-radiant.rb'

Style/GlobalVars:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
